FROM node:18-alpine AS builder

WORKDIR /app

ARG ENV_FILE=.env
COPY ${ENV_FILE} .env

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
RUN npm run export

FROM nginx:alpine

COPY --from=builder /app/out /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
